CREATE DATABASE one_cloud;
USE one_cloud;

CREATE TABLE user (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	account VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(20) NOT NULL,
	nickname VARCHAR(30) NOT NULL,
	photo_url VARCHAR(255) NOT NULL,
	used_capacity INT UNSIGNED NOT NULL,
	safe_password VARCHAR(20)
);

CREATE TABLE file (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	md5 CHAR(32) NOT NULL UNIQUE,
	size INT UNSIGNED NOT NULL,
	type VARCHAR(10) NOT NULL,
	url VARCHAR(255) NOT NULL
);

CREATE TABLE local_file (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	file_id BIGINT UNSIGNED NOT NULL,
	local_name VARCHAR(255) NOT NULL,
	local_type VARCHAR(10),
	last_modified_time DATETIME NOT NULL,
	parent BIGINT UNSIGNED NOT NULL
);

CREATE TABLE local_folder (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id INT UNSIGNED,
	local_name VARCHAR(255) NOT NULL,
	last_modified_time DATETIME,
	parent BIGINT UNSIGNED
);